#!/bin/bash
#SBATCH -c 2
#SBATCH --gres=gpu:4
#SBATCH --partition=gpu
#SBATCH --time=1:00:00
#SBATCH --ntasks-per-core=4
#SBATCH --output=GPU.out
#SBATCH --partition=gpu
module load python/3.10.9 cuda
conda activate cupyenv
cd gpu_soens
python gpu_sim.py

